env:
  global:
    # Doctr deploy key for sympy/sympy.github.com
    - secure: "mPi/pjnsoaI+yKDrZmYx31UtGVrkh6Z8IbYSEDwowmPWYzaRgp7fvyj6UfzowOAlR43razqnWOZhkizOiUUChQnMCQrcV1OAfaXsMpf4Xvqn9JBytZeKgksTkyegBAlqnW56+RDvz4cUldBusrOiVC2hEHsffLbwcGH9ARMfoTc="

script:
  - set -e
  - ./generate
  - pip install doctr
  - doctr deploy --built-docs . .
